## WiSHFUL Agent config file

agent_info:
  name: 'lte'
  info: 'agent_info'
  iface: 'eth0'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"eth0", "groupName":"tcd_hydra"}

  gnuradio:
      module : wishful_module_gnuradio
      class_name : GnuRadioModule
      interfaces : ['usrp', ]
